apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    application: {{.Values.applicationName}}
  name: {{.Values.applicationName}}
spec:
  replicas: 1
  selector:
    deploymentConfig: {{.Values.applicationName}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: {{.Values.applicationName}}
        deploymentConfig: {{.Values.applicationName}}
      name: {{.Values.applicationName}}
    spec:
      containers:
        image: {{.Values.applicationName}}
        imagePullPolicy: Always
        name: {{.Values.applicationName}}
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -s 'http://localhost:8080{{.Values.readinessPath}}' | grep -iq {{.Values.readinessResponse}}'
      terminationGracePeriodSeconds: 60
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{.Values.applicationName}}
      from:
        kind: ImageStreamTag
        name: {{.Values.applicationName}}:latest
    type: ImageChange
  - type: ConfigChange