apiVersion: route.openshift.io/v1
id:  {{.Values.applicationName}}-http
kind: Route
metadata:
  annotations:
    description: Route for application's http service.
  labels:
    application:  {{.Values.applicationName}}
  name:  {{.Values.applicationName}}
spec:
  host:  {{.Values.hostname}}
  to:
    name:  {{.Values.applicationName}}