{{- $baseName := .Values.baseName -}}
{{- $friendlyBaseName := .Values.friendlyBaseName -}}
{{- range .Values.environments }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: "{{ $baseName }}-{{ . }}"
  annotations:
    openshift.io/display-name: "{{ $friendlyBaseName }} - {{ . | title }}"
    openshift.io/sa.scc.mcs: s0:c11,c5
    openshift.io/sa.scc.supplemental-groups: 1000120000/10000
    openshift.io/sa.scc.uid-range: 1000120000/10000
{{- end}}