kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: project-pipeline-operator
rules:
- apiGroups:
  - cop.redhat.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - project.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - rolebindings
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: project-pipeline-default-account-project-pipeline-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: project-pipeline
roleRef:
  kind: ClusterRole
  name: helm-app-operator
apiGroup: rbac.authorization.k8s.io