apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: {{.Values.applicationName}}
  name: {{.Values.applicationName}}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: {{.Values.applicationName}}