apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: springbootapps.cop.redhat.com
spec:
  group: cop.redhat.com
  names:
    kind: SpringBootApp
    listKind: SpringBootAppList
    plural: springbootapps
    singular: springbootapp
  scope: Namespaced
  version: v1alpha1